#!/usr/bin/env python

import sys

from config import config
from app.application import Application


def usage():
    msg = """
Usage:
    ad-stats <path/to/file.xlsx>
"""
    print(msg)


if __name__ == "__main__":
    # TODO?: add more cli params
    try:
        config["input_file"] = sys.argv[1]
    except IndexError:
        usage()
        sys.exit(1)
    app = Application(config)
    app.run()
