#!/usr/bin/env python

import logging
import os
import sys

import argparse
import configparser

from server.options import Options
from server import create_server


def get_logger(quiet, verbose):
    lvl = logging.FATAL if quiet \
            else logging.DEBUG if verbose \
            else logging.INFO
    return logging.basicConfig(
        level=lvl,
        format="%(asctime)-25s%(levelname)-10s%(message)s"
    )


def get_command_line_options():
    parser = argparse.ArgumentParser(description="Ad statistics server")
    parser.add_argument("-c", "--config",
                        metavar="CONFIG_FILE",
                        dest="config",
                        type=str,
                        default="options.ini",
                        help="Use specified configuration file")
    verbosity = parser.add_mutually_exclusive_group()
    verbosity.add_argument("-v", "--verbose",
                           action="store_true",
                           default=False,
                           help="Be more talkative")
    verbosity.add_argument("-q", "--quiet",
                           action="store_true",
                           default=False,
                           help="Suppress any output")
    parser.add_argument("-d", "--daemonize",
                        action="store_true",
                        default=False,
                        help="Start as daemon")
    return parser.parse_args()


def read_config(filename):
    if not os.path.isabs(filename):
        filename = os.path.join(os.getcwd(), filename)
    if not os.path.isfile(filename):
        logging.fatal("No such file (%s)", filename)
        sys.exit(-1)
    config = configparser.ConfigParser()
    config.read(filename)
    return Options(config)


def start_server(config, debug=False):
    opts = config.server_options()
    app = create_server(config)
    app.run(opts["listen_address"],
            port=opts["listen_port"],
            debug=debug)


def main():
    options = get_command_line_options()
    get_logger(options.quiet, options.verbose)
    config = read_config(options.config)
    start_server(config, debug=options.verbose)


if __name__ == "__main__":
    main()
