#!env/bin/python

from gevent.pywsgi import WSGIServer

from base import *


if __name__ == "__main__":
    options = get_command_line_options()
    get_logger(options.quiet, options.verbose)
    config = read_config(options.config)
    opts = config.server_options()
    app = make_server(config, debug=options.verbose)
    if options.gevent:
        server = WSGIServer((opts["listen_address"], opts["listen_port"]), app)
        server.serve_forever()
    else:
        app.run(opts["listen_address"],
                port=opts["listen_port"],
                debug=options.verbose)
